spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  messages:
    basename: messages
    encoding: UTF-8
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
exam:
  cookie:
    secure: false
  question:
    image:
      srcPattern: https://kennet.server-on.net/exam_images/questions/E{0}Q{1}.jpg
      numberFormat: '%03d'
      uploadPath: C:/test_images/questions
      filenamePattern: E{0}Q{1}.jpg
server:
  port: 8080
  servlet:
    context-path: /exam
    session:
      timeout: 60
logging:
  file: logs/exam.log
---
spring:
  profiles: junit
  messages:
    basename: messages
    encoding: UTF-8
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
exam:
  cookie:
    secure: false
  question:
    image:
      srcPattern: https://kennet.server-on.net/exam_images/questions/E{0}Q{1}.jpg
      numberFormat: '%03d'
      uploadPath: C:/test_images/questions
      filenamePattern: E{0}Q{1}.jpg
server:
  port: 8080
  servlet:
    context-path: /exam
    session:
      timeout: 1800
logging:
  file: logs/exam.log
---
spring:
  profiles: prod
  messages:
    basename: messages
    encoding: UTF-8
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
exam:
  cookie:
    secure: true
  question:
    image:
      srcPattern: https://kennet.server-on.net/exam_images/questions/E{0}Q{1}.jpg
      numberFormat: '%03d'
      uploadPath: /var/myapp/kennet_exam/images/questions
      filenamePattern: E{0}Q{1}.jpg
server:
  port: 8080
  servlet:
    context-path: /exam
    session:
      timeout: 1800000
logging:
  file: logs/exam.log
